// src/components/NavBar.tsx
import { NavLink } from "react-router-dom";

const links = [
  { href: "/", label: "Overview" },
  { href: "/approvals", label: "Approvals" },
  { href: "/incidents", label: "Incidents" },
  { href: "/reissue", label: "Reissue" },
  { href: "/governance", label: "Governance" },
];

function NavBar() {
  return (
    <nav className="card nav">
      {links.map((link) => (
        <NavLink
          key={link.href}
          to={link.href}
          className={({ isActive }) => (isActive ? "active" : undefined)}
          end={link.href === "/"}
        >
          {link.label}
        </NavLink>
      ))}
    </nav>
  );
}

export default NavBar;

// src/components/NavBar.vue
<template>
  <nav class="card nav">
    <RouterLink v-for="link in links" :key="link.href" :to="link.href">{{ link.label }}</RouterLink>
  </nav>
</template>

<script setup lang="ts">
const links = [
  { href: "/", label: "Overview" },
  { href: "/approvals", label: "Approvals" },
  { href: "/incidents", label: "Incidents" },
  { href: "/reissue", label: "Reissue" },
  { href: "/governance", label: "Governance" }
];
</script>
